while True:
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
    print("正在压测CPU.......")
    print("正在烧烤CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print("正在压测CPU.......")
    print(1+115)
    print("Fxxk You!Shit!")
array = [1, 3, 5]
for x in array:
    print(array)